name: Terraform Multi-Region Infrastructure Deployment

on:
  push:
    branches:
      - devops-pipeline
  workflow_dispatch:

env:
  TF_VERSION: 1.6.2
  WORKING_DIR: ./main

jobs:
  terraform:
    name: Terraform Apply Multi-Region
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      # 3️⃣ Configure AWS credentials (use ap-south-1 as default entrypoint)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # 4️⃣ Terraform Init
      - name: Terraform Init
        working-directory: ${{ env.WORKING_DIR }}
        run: terraform init -input=false

      # 5️⃣ Terraform Validate
      - name: Terraform Validate
        working-directory: ${{ env.WORKING_DIR }}
        run: terraform validate

      # 6️⃣ Terraform Plan
      - name: Terraform Plan
        working-directory: ${{ env.WORKING_DIR }}
        run: terraform plan -input=false -out=tfplan

      # 7️⃣ Terraform Apply
      - name: Terraform Apply
        working-directory: ${{ env.WORKING_DIR }}
        run: terraform apply -input=false -auto-approve tfplan

      # 8️⃣ Terraform Output
      - name: Terraform Output
        working-directory: ${{ env.WORKING_DIR }}
        run: terraform output

